import { Property } from '@/types/property';

export const mockProperties: Property[] = [
  {
    id: 'atlantico-shopping',
    title: 'Atlântico Shopping',
    slug: 'atlantico-shopping',
    type: 'apartment',
    category: 'third_party',
    status: 'available',
    price: 2368000,
    area: 126.03,
    bedrooms: 3,
    suites: 1,
    bathrooms: 2,
    parking: 1,
    address: {
      street: 'Avenida Brasil, 1271',
      neighborhood: 'Centro',
      city: 'Balneário Camboriú',
      state: 'SC',
    },
    images: [
      '/images/properties/atlantico-shopping/1.jpg',
      '/images/properties/atlantico-shopping/2.jpg',
      '/images/properties/atlantico-shopping/3.jpg',
      '/images/properties/atlantico-shopping/4.jpg'
    ],
    description: 'Excelente apartamento no Atlântico Shopping. O imóvel conta com 126,03 m² de área privativa, 3 dormitórios sendo 1 suíte, 2 banheiros, sala de estar e 1 vaga de garagem. O condomínio oferece infraestrutura com piscina e portaria 24hs, localizado na Avenida Brasil em Balneário Camboriú/SC.',
    features: ['Piscina', 'Sala de Estar', 'Portaria 24hs'],
    highlighted: true,
    createdAt: '2025-11-15T10:00:00Z',
  },
  {
    id: 'apartamento-centro-bc',
    title: 'Apartamento no Coração de BC',
    slug: 'apartamento-centro-bc',
    type: 'apartment',
    category: 'launch',
    status: 'available',
    price: 7010000,
    area: 0,
    bedrooms: 0,
    suites: 0,
    bathrooms: 0,
    parking: 0,
    address: {
      neighborhood: 'Centro',
      city: 'Balneário Camboriú',
      state: 'SC',
    },
    images: [
      '/images/properties/apartamento-centro-bc/CIA_Fachada_C2_EF.jpg-name-fdf7b540b65557378800ef0a8e8c7aa99ee3d351e3f85f5c35d28ef851985793.webp',
      '/images/properties/apartamento-centro-bc/CIA_Fachada_C4_EF.jpg-name-8ec6965be80fa90924b16498fcd00dde5c547bdf61b3281185eb5b6134ed321d.webp',
      '/images/properties/apartamento-centro-bc/CIA_Fachada_C7_EF.jpg-name-a8ad5486b461ef7154cce5bc12d427dfd9bdd5fd0ef38fd7390bf6c62a07486c.webp',
      '/images/properties/apartamento-centro-bc/CIA_ITA_Fachada_Coroamento_EF.jpg-name-ee6477b0e7e956d95fb86cbd1516eb70b5325b4273763a46425ce2e1ffbae45d.webp'
    ],
    description: 'O apartamento que você sempre quis morar, no coração de Balneário Camboriú.',
    features: ['Sala de Estar', 'Piscina infantil', 'Entrada p/ banhistas e box de praia'],
    highlighted: true,
    createdAt: '2026-06-19T10:00:00Z',
  },
  {
    id: 'residencial-le-visage',
    title: 'Residencial Lê Visage',
    slug: 'residencial-le-visage',
    type: 'apartment',
    category: 'launch',
    status: 'available',
    price: 8500000,
    area: 170,
    bedrooms: 4,
    suites: 4,
    bathrooms: 4,
    parking: 4,
    address: {
      neighborhood: 'Centro',
      city: 'Balneário Camboriú',
      state: 'SC',
    },
    images: [
      '/images/properties/residencial-le-visage/WhatsApp Image 2026-06-10 at 13.43.56 (1).jpeg',
      '/images/properties/residencial-le-visage/WhatsApp Image 2026-06-10 at 13.43.56 (2).jpeg',
      '/images/properties/residencial-le-visage/WhatsApp Image 2026-06-10 at 13.43.56 (3).jpeg',
      '/images/properties/residencial-le-visage/WhatsApp Image 2026-06-10 at 13.43.56 (4).jpeg',
      '/images/properties/residencial-le-visage/WhatsApp Image 2026-06-10 at 13.43.56.jpeg',
      '/images/properties/residencial-le-visage/WhatsApp Image 2026-06-10 at 13.43.57 (1).jpeg',
      '/images/properties/residencial-le-visage/WhatsApp Image 2026-06-10 at 13.43.57 (2).jpeg',
      '/images/properties/residencial-le-visage/WhatsApp Image 2026-06-10 at 13.43.57 (3).jpeg',
      '/images/properties/residencial-le-visage/WhatsApp Image 2026-06-10 at 13.43.57.jpeg',
      '/images/properties/residencial-le-visage/WhatsApp Image 2026-06-10 at 13.43.58 (1).jpeg',
      '/images/properties/residencial-le-visage/WhatsApp Image 2026-06-10 at 13.43.58 (2).jpeg',
      '/images/properties/residencial-le-visage/WhatsApp Image 2026-06-10 at 13.43.58 (3).jpeg',
      '/images/properties/residencial-le-visage/WhatsApp Image 2026-06-10 at 13.43.58 (4).jpeg',
      '/images/properties/residencial-le-visage/WhatsApp Image 2026-06-10 at 13.43.58.jpeg',
      '/images/properties/residencial-le-visage/WhatsApp Image 2026-06-10 at 13.43.59 (1).jpeg',
      '/images/properties/residencial-le-visage/WhatsApp Image 2026-06-10 at 13.43.59 (2).jpeg',
      '/images/properties/residencial-le-visage/WhatsApp Image 2026-06-10 at 13.43.59 (3).jpeg',
      '/images/properties/residencial-le-visage/WhatsApp Image 2026-06-10 at 13.43.59 (4).jpeg',
      '/images/properties/residencial-le-visage/WhatsApp Image 2026-06-10 at 13.43.59 (5).jpeg',
      '/images/properties/residencial-le-visage/WhatsApp Image 2026-06-10 at 13.43.59.jpeg'
    ],
    description: 'Residencial Lê Visage no coração de Balneário Camboriú. Com 170m² privativos, 4 suítes, 4 vagas de garagem. Finamente mobiliado, lazer completo, a apenas 40m do mar e com vista para o mar.',
    features: ['Finamente mobiliado', 'Lazer completo', '40 m do mar', 'Vista mar'],
    highlighted: true,
    createdAt: '2026-06-19T10:05:00Z',
  },
  {
    id: 'ed-ocean-breazze',
    title: 'Ed. Ocean Breazze',
    slug: 'ed-ocean-breazze',
    type: 'apartment',
    category: 'third_party',
    status: 'available',
    price: 4100000,
    area: 167,
    bedrooms: 4,
    bathrooms: 4,
    parking: 3,
    address: {
      neighborhood: 'Centro',
      city: 'Balneário Camboriú',
      state: 'SC',
    },
    images: [
      '/images/properties/ed-ocean-breazze/WhatsApp Image 2026-06-10 at 13.45.02 (1).jpeg',
      '/images/properties/ed-ocean-breazze/WhatsApp Image 2026-06-10 at 13.45.02 (2).jpeg',
      '/images/properties/ed-ocean-breazze/WhatsApp Image 2026-06-10 at 13.45.02 (3).jpeg',
      '/images/properties/ed-ocean-breazze/WhatsApp Image 2026-06-10 at 13.45.02 (4).jpeg',
      '/images/properties/ed-ocean-breazze/WhatsApp Image 2026-06-10 at 13.45.02.jpeg',
      '/images/properties/ed-ocean-breazze/WhatsApp Image 2026-06-10 at 13.45.03 (1).jpeg',
      '/images/properties/ed-ocean-breazze/WhatsApp Image 2026-06-10 at 13.45.03 (2).jpeg',
      '/images/properties/ed-ocean-breazze/WhatsApp Image 2026-06-10 at 13.45.03 (3).jpeg',
      '/images/properties/ed-ocean-breazze/WhatsApp Image 2026-06-10 at 13.45.03 (4).jpeg',
      '/images/properties/ed-ocean-breazze/WhatsApp Image 2026-06-10 at 13.45.03.jpeg',
      '/images/properties/ed-ocean-breazze/WhatsApp Image 2026-06-10 at 13.45.04.jpeg'
    ],
    description: 'Apto 1401 no Ed. Ocean Breazze, localizado no coração de Balneário Camboriú. Com 167m² privativos, 4 suítes e finamente mobiliado. Conta com 3 vagas de garagem, lazer completo e linda vista para o mar.',
    features: ['Finamente mobiliado', 'Lazer completo', 'Vista para o mar'],
    highlighted: true,
    createdAt: '2026-06-19T10:10:00Z',
  },
  {
    id: 'edificio-parigi-residenza',
    title: 'Edifício Parigi Residenza',
    slug: 'edificio-parigi-residenza',
    type: 'apartment',
    category: 'third_party',
    status: 'available',
    price: 5800000,
    area: 161,
    bedrooms: 4,
    bathrooms: 4,
    parking: 3,
    address: {
      neighborhood: 'Centro',
      city: 'Balneário Camboriú',
      state: 'SC',
    },
    images: [
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.52 (1).jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.52 (2).jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.52 (3).jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.52.jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.53 (1).jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.53 (2).jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.53 (3).jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.53 (4).jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.53.jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.54 (1).jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.54 (2).jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.54 (3).jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.54 (4).jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.54.jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.55 (1).jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.55 (2).jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.55 (3).jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.55 (4).jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.55.jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.56 (1).jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.56 (2).jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.56 (3).jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.56 (4).jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.56.jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.57 (1).jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.57 (2).jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.57 (3).jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.57 (4).jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.57 (5).jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.57.jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.58 (1).jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.58 (2).jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.58 (3).jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.58 (4).jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.58.jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.59 (1).jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.59 (2).jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.59 (3).jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.59 (4).jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.59 (5).jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.51.59.jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.52.00 (1).jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.52.00 (2).jpeg',
      '/images/properties/edificio-parigi-residenza/WhatsApp Image 2026-06-10 at 13.52.00.jpeg'
    ],
    description: 'Apartamento à venda no Edifício Parigi Residenza, construtora Embraed, de frente para a Avenida Brasil no coração de Balneário Camboriú. São 161m² privativos, 04 dormitórios (sendo 02 suítes), amplo living integrado, finamente mobiliado e decorado. Conta com 03 vagas de garagem e lazer completo. Valor à vista: R$ 5.800.000,00 ou R$ 6.500.000,00 com permuta.',
    features: ['Frente Avenida Brasil', 'Mobiliado e decorado', 'Construtora Embraed', 'Lazer completo'],
    highlighted: true,
    createdAt: '2026-06-19T10:20:00Z',
  },
  {
    id: 'ed-farol-ponta-do-mel',
    title: 'Ed. Farol Ponta do Mel',
    slug: 'ed-farol-ponta-do-mel',
    type: 'apartment',
    category: 'third_party',
    status: 'available',
    price: 1700000,
    area: 126.51,
    bedrooms: 2,
    bathrooms: 3,
    parking: 2,
    address: {
      street: 'Rua Egídio Alfredo Crispim n°55',
      neighborhood: 'Pioneiros',
      city: 'Balneário Camboriú',
      state: 'SC',
    },
    images: [
      '/images/properties/ed-farol-ponta-do-mel/WhatsApp Image 2026-06-10 at 17.06.44 (1).jpeg',
      '/images/properties/ed-farol-ponta-do-mel/WhatsApp Image 2026-06-10 at 17.06.44 (2).jpeg',
      '/images/properties/ed-farol-ponta-do-mel/WhatsApp Image 2026-06-10 at 17.06.44 (3).jpeg',
      '/images/properties/ed-farol-ponta-do-mel/WhatsApp Image 2026-06-10 at 17.06.44.jpeg',
      '/images/properties/ed-farol-ponta-do-mel/WhatsApp Image 2026-06-10 at 17.06.45 (1).jpeg',
      '/images/properties/ed-farol-ponta-do-mel/WhatsApp Image 2026-06-10 at 17.06.45 (2).jpeg',
      '/images/properties/ed-farol-ponta-do-mel/WhatsApp Image 2026-06-10 at 17.06.45 (3).jpeg',
      '/images/properties/ed-farol-ponta-do-mel/WhatsApp Image 2026-06-10 at 17.06.45 (4).jpeg',
      '/images/properties/ed-farol-ponta-do-mel/WhatsApp Image 2026-06-10 at 17.06.45.jpeg',
      '/images/properties/ed-farol-ponta-do-mel/WhatsApp Image 2026-06-10 at 17.06.46 (1).jpeg',
      '/images/properties/ed-farol-ponta-do-mel/WhatsApp Image 2026-06-10 at 17.06.46 (2).jpeg',
      '/images/properties/ed-farol-ponta-do-mel/WhatsApp Image 2026-06-10 at 17.06.46 (3).jpeg',
      '/images/properties/ed-farol-ponta-do-mel/WhatsApp Image 2026-06-10 at 17.06.46 (4).jpeg',
      '/images/properties/ed-farol-ponta-do-mel/WhatsApp Image 2026-06-10 at 17.06.46 (5).jpeg',
      '/images/properties/ed-farol-ponta-do-mel/WhatsApp Image 2026-06-10 at 17.06.46.jpeg',
      '/images/properties/ed-farol-ponta-do-mel/WhatsApp Image 2026-06-10 at 17.06.47 (1).jpeg',
      '/images/properties/ed-farol-ponta-do-mel/WhatsApp Image 2026-06-10 at 17.06.47 (2).jpeg',
      '/images/properties/ed-farol-ponta-do-mel/WhatsApp Image 2026-06-10 at 17.06.47 (3).jpeg',
      '/images/properties/ed-farol-ponta-do-mel/WhatsApp Image 2026-06-10 at 17.06.47 (4).jpeg',
      '/images/properties/ed-farol-ponta-do-mel/WhatsApp Image 2026-06-10 at 17.06.47.jpeg',
      '/images/properties/ed-farol-ponta-do-mel/WhatsApp Image 2026-06-10 at 17.06.48 (1).jpeg',
      '/images/properties/ed-farol-ponta-do-mel/WhatsApp Image 2026-06-10 at 17.06.48 (2).jpeg',
      '/images/properties/ed-farol-ponta-do-mel/WhatsApp Image 2026-06-10 at 17.06.48 (3).jpeg',
      '/images/properties/ed-farol-ponta-do-mel/WhatsApp Image 2026-06-10 at 17.06.48.jpeg'
    ],
    description: 'Apto 1802 no Ed. Farol Ponta do Mel, localizado na Rua Egídio Alfredo Crispim n°55, bairro Pioneiros. Conta com 126,51 m² de área total, 02 suítes, lavabo, cozinha integrada e churrasqueira a carvão. Possui 02 vagas de garagem privativas (32/42) e lazer completo no condomínio.',
    features: ['Churrasqueira a carvão', 'Cozinha integrada', 'Lazer completo'],
    highlighted: true,
    createdAt: '2026-06-19T10:30:00Z',
  },
  {
    id: 'ed-res-basualdo-torre-b',
    title: 'Ed. Res. Basualdo Torre B',
    slug: 'ed-res-basualdo-torre-b',
    type: 'apartment',
    category: 'third_party',
    status: 'available',
    price: 1600000,
    area: 86.66,
    bedrooms: 3,
    bathrooms: 2,
    parking: 2,
    address: {
      street: 'Rua 3250 n° 300',
      neighborhood: 'Centro',
      city: 'Balneário Camboriú',
      state: 'SC',
    },
    images: [
      '/images/properties/ed-res-basualdo-torre-b/WhatsApp Image 2026-06-10 at 17.07.47 (1).jpeg',
      '/images/properties/ed-res-basualdo-torre-b/WhatsApp Image 2026-06-10 at 17.07.47 (2).jpeg',
      '/images/properties/ed-res-basualdo-torre-b/WhatsApp Image 2026-06-10 at 17.07.47 (3).jpeg',
      '/images/properties/ed-res-basualdo-torre-b/WhatsApp Image 2026-06-10 at 17.07.47 (4).jpeg',
      '/images/properties/ed-res-basualdo-torre-b/WhatsApp Image 2026-06-10 at 17.07.47.jpeg',
      '/images/properties/ed-res-basualdo-torre-b/WhatsApp Image 2026-06-10 at 17.07.48 (1).jpeg',
      '/images/properties/ed-res-basualdo-torre-b/WhatsApp Image 2026-06-10 at 17.07.48 (2).jpeg',
      '/images/properties/ed-res-basualdo-torre-b/WhatsApp Image 2026-06-10 at 17.07.48 (3).jpeg',
      '/images/properties/ed-res-basualdo-torre-b/WhatsApp Image 2026-06-10 at 17.07.48 (4).jpeg',
      '/images/properties/ed-res-basualdo-torre-b/WhatsApp Image 2026-06-10 at 17.07.48.jpeg',
      '/images/properties/ed-res-basualdo-torre-b/WhatsApp Image 2026-06-10 at 17.07.49 (1).jpeg',
      '/images/properties/ed-res-basualdo-torre-b/WhatsApp Image 2026-06-10 at 17.07.49 (2).jpeg',
      '/images/properties/ed-res-basualdo-torre-b/WhatsApp Image 2026-06-10 at 17.07.49 (3).jpeg',
      '/images/properties/ed-res-basualdo-torre-b/WhatsApp Image 2026-06-10 at 17.07.49.jpeg'
    ],
    description: 'Apto 601 no Ed. Res. Basualdo Torre B, localizado na Rua 3250 n° 300. Área privativa de 86,66 m², contendo 01 suíte, 02 dormitórios e 01 lavabo. Cozinha e sala integradas, lavanderia e sacada fechada com churrasqueira a carvão. Possui 02 vagas individuais privativas (29 e 30). Condomínio: R$ 560,00 e IPTU: R$ 106,00.',
    features: ['Sacada fechada', 'Churrasqueira a carvão', 'Cozinha integrada', 'Vagas individuais'],
    highlighted: true,
    createdAt: '2026-06-19T10:40:00Z',
  },
  {
    id: 'hamptons-village',
    title: 'Hamptons Village - Cobertura Duplex',
    slug: 'hamptons-village',
    type: 'apartment',
    category: 'third_party',
    status: 'available',
    price: 7900000,
    area: 240.92,
    bedrooms: 3,
    bathrooms: 4,
    parking: 4,
    address: {
      neighborhood: 'Centro',
      city: 'Balneário Camboriú',
      state: 'SC',
    },
    images: [
      '/images/properties/hamptons-village/PHOTO-2023-06-15-21-08-44.jpg',
      '/images/properties/hamptons-village/PHOTO-2023-06-15-21-08-44_1.jpg',
      '/images/properties/hamptons-village/PHOTO-2023-06-15-21-08-44_10.jpg',
      '/images/properties/hamptons-village/PHOTO-2023-06-15-21-08-44_11.jpg',
      '/images/properties/hamptons-village/PHOTO-2023-06-15-21-08-44_12.jpg',
      '/images/properties/hamptons-village/PHOTO-2023-06-15-21-08-44_13.jpg',
      '/images/properties/hamptons-village/PHOTO-2023-06-15-21-08-44_14.jpg',
      '/images/properties/hamptons-village/PHOTO-2023-06-15-21-08-44_15.jpg',
      '/images/properties/hamptons-village/PHOTO-2023-06-15-21-08-44_16.jpg',
      '/images/properties/hamptons-village/PHOTO-2023-06-15-21-08-44_17.jpg',
      '/images/properties/hamptons-village/PHOTO-2023-06-15-21-08-44_18.jpg',
      '/images/properties/hamptons-village/PHOTO-2023-06-15-21-08-44_19.jpg',
      '/images/properties/hamptons-village/PHOTO-2023-06-15-21-08-44_2.jpg',
      '/images/properties/hamptons-village/PHOTO-2023-06-15-21-08-44_20.jpg',
      '/images/properties/hamptons-village/PHOTO-2023-06-15-21-08-44_21.jpg',
      '/images/properties/hamptons-village/PHOTO-2023-06-15-21-08-44_22.jpg',
      '/images/properties/hamptons-village/PHOTO-2023-06-15-21-08-44_23.jpg',
      '/images/properties/hamptons-village/PHOTO-2023-06-15-21-08-44_24.jpg',
      '/images/properties/hamptons-village/PHOTO-2023-06-15-21-08-44_25.jpg',
      '/images/properties/hamptons-village/PHOTO-2023-06-15-21-08-44_26.jpg',
      '/images/properties/hamptons-village/PHOTO-2023-06-15-21-08-44_27.jpg',
      '/images/properties/hamptons-village/PHOTO-2023-06-15-21-08-44_28.jpg',
      '/images/properties/hamptons-village/PHOTO-2023-06-15-21-08-44_3.jpg',
      '/images/properties/hamptons-village/PHOTO-2023-06-15-21-08-44_4.jpg',
      '/images/properties/hamptons-village/PHOTO-2023-06-15-21-08-44_5.jpg',
      '/images/properties/hamptons-village/PHOTO-2023-06-15-21-08-44_6.jpg',
      '/images/properties/hamptons-village/PHOTO-2023-06-15-21-08-44_7.jpg',
      '/images/properties/hamptons-village/PHOTO-2023-06-15-21-08-44_8.jpg',
      '/images/properties/hamptons-village/PHOTO-2023-06-15-21-08-44_9.jpg',
      '/images/properties/hamptons-village/image_11.jpg',
      '/images/properties/hamptons-village/image_12.jpg',
      '/images/properties/hamptons-village/image_28.jpg',
      '/images/properties/hamptons-village/image_3.jpg',
      '/images/properties/hamptons-village/image_4.jpg'
    ],
    description: 'Cobertura Duplex 3202 no Hamptons Village da construtora Embraed, a apenas 400m do mar. Conta com 240,92 m² de área privativa, 03 suítes (sendo 01 master), área de festas privativa com churrasqueira a carvão e piscina privativa. 04 vagas de garagem (duas duplas). É finamente mobiliado, decorado e equipado. O empreendimento oferece ampla área de lazer com mais de 1.700m².',
    features: ['Piscina privativa', 'Cobertura Duplex', 'Construtora Embraed', '4 vagas'],
    highlighted: true,
    createdAt: '2026-06-19T10:50:00Z',
  },
  {
    id: 'edificio-cartagena-residence',
    title: 'Edifício Cartagena Residence',
    slug: 'edificio-cartagena-residence',
    type: 'apartment',
    category: 'third_party',
    status: 'available',
    price: 3550000,
    area: 134.56,
    bedrooms: 3,
    bathrooms: 4,
    parking: 2,
    address: {
      street: 'Rua 3610, nº 14',
      neighborhood: 'Centro',
      city: 'Balneário Camboriú',
      state: 'SC',
    },
    images: [
      '/images/properties/edificio-cartagena-residence/IMG_6457.jpeg',
      '/images/properties/edificio-cartagena-residence/IMG_6458.jpeg',
      '/images/properties/edificio-cartagena-residence/IMG_6459.jpeg',
      '/images/properties/edificio-cartagena-residence/IMG_6460.jpeg',
      '/images/properties/edificio-cartagena-residence/IMG_6461.jpeg',
      '/images/properties/edificio-cartagena-residence/IMG_6465.jpeg',
      '/images/properties/edificio-cartagena-residence/IMG_6466.jpeg',
      '/images/properties/edificio-cartagena-residence/IMG_6467.jpeg',
      '/images/properties/edificio-cartagena-residence/IMG_6470.jpeg',
      '/images/properties/edificio-cartagena-residence/IMG_6471.jpeg',
      '/images/properties/edificio-cartagena-residence/IMG_6472.jpeg',
      '/images/properties/edificio-cartagena-residence/IMG_6473.jpeg',
      '/images/properties/edificio-cartagena-residence/IMG_6474.jpeg',
      '/images/properties/edificio-cartagena-residence/IMG_6475.jpeg',
      '/images/properties/edificio-cartagena-residence/IMG_6476.jpeg',
      '/images/properties/edificio-cartagena-residence/IMG_6477.jpeg',
      '/images/properties/edificio-cartagena-residence/IMG_6480.jpeg',
      '/images/properties/edificio-cartagena-residence/IMG_6481.jpeg',
      '/images/properties/edificio-cartagena-residence/IMG_6482.jpeg',
      '/images/properties/edificio-cartagena-residence/IMG_6521.jpeg',
      '/images/properties/edificio-cartagena-residence/IMG_6522.jpeg',
      '/images/properties/edificio-cartagena-residence/IMG_6523.jpeg',
      '/images/properties/edificio-cartagena-residence/IMG_6524.jpeg',
      '/images/properties/edificio-cartagena-residence/IMG_6525.jpeg',
      '/images/properties/edificio-cartagena-residence/IMG_6526.jpeg',
      '/images/properties/edificio-cartagena-residence/IMG_6527.jpeg',
      '/images/properties/edificio-cartagena-residence/IMG_6528.jpeg',
      '/images/properties/edificio-cartagena-residence/IMG_6529.jpeg'
    ],
    description: 'Apartamento mobiliado, decorado e equipado no Edifício Cartagena Residence (Construtora RV) localizado no Centro de Balneário Camboriú, na Avenida Brasil. Conta com 134,56m² de área privativa, 03 suítes, lavabo, amplo living integrado com cozinha e espaço gourmet. Possui 02 vagas de garagem. O empreendimento conta com 1200m² de área de lazer completa incluindo piscina, cinema, spa e salões de festas.',
    features: ['Espaço gourmet', 'Lazer completo', 'Construtora RV', 'Persianas automatizadas'],
    highlighted: true,
    createdAt: '2026-06-19T11:00:00Z',
  },
  {
    id: 'sun-beach-residence',
    title: 'Sun Beach Residence',
    slug: 'sun-beach-residence',
    type: 'apartment',
    category: 'third_party',
    status: 'available',
    price: 3490000,
    area: 149.43,
    bedrooms: 4,
    bathrooms: 4,
    parking: 3,
    address: {
      street: 'Rua 3140, n.202',
      neighborhood: 'Centro',
      city: 'Balneário Camboriú',
      state: 'SC',
    },
    images: [
      '/images/properties/sun-beach-residence/IMG_8263.jpeg',
      '/images/properties/sun-beach-residence/IMG_8264.jpeg',
      '/images/properties/sun-beach-residence/IMG_8266.jpeg',
      '/images/properties/sun-beach-residence/IMG_8267.jpeg',
      '/images/properties/sun-beach-residence/IMG_8268.jpeg',
      '/images/properties/sun-beach-residence/IMG_8269.jpeg',
      '/images/properties/sun-beach-residence/IMG_8273.jpeg',
      '/images/properties/sun-beach-residence/IMG_8274.jpeg',
      '/images/properties/sun-beach-residence/IMG_8275.jpeg',
      '/images/properties/sun-beach-residence/IMG_8278.jpeg',
      '/images/properties/sun-beach-residence/IMG_8279.jpeg',
      '/images/properties/sun-beach-residence/IMG_8280.jpeg',
      '/images/properties/sun-beach-residence/IMG_8281.jpeg',
      '/images/properties/sun-beach-residence/IMG_8282.jpeg',
      '/images/properties/sun-beach-residence/IMG_8283.jpeg',
      '/images/properties/sun-beach-residence/IMG_8285.jpeg',
      '/images/properties/sun-beach-residence/IMG_8288.jpeg',
      '/images/properties/sun-beach-residence/IMG_8289.jpeg',
      '/images/properties/sun-beach-residence/IMG_8290.jpeg',
      '/images/properties/sun-beach-residence/IMG_8292.jpeg',
      '/images/properties/sun-beach-residence/IMG_8293.jpeg',
      '/images/properties/sun-beach-residence/IMG_8294.jpeg',
      '/images/properties/sun-beach-residence/IMG_8322.jpeg',
      '/images/properties/sun-beach-residence/IMG_8323.jpeg',
      '/images/properties/sun-beach-residence/IMG_8324.jpeg',
      '/images/properties/sun-beach-residence/IMG_8325.jpeg',
      '/images/properties/sun-beach-residence/IMG_8327.jpeg',
      '/images/properties/sun-beach-residence/IMG_8328.jpeg',
      '/images/properties/sun-beach-residence/IMG_8329.jpeg',
      '/images/properties/sun-beach-residence/IMG_8331.jpeg',
      '/images/properties/sun-beach-residence/IMG_8332.jpeg'
    ],
    description: 'Apto 1201 no Sun Beach Residence localizado na Rua 3140, n.202 em Balneário Camboriú. Conta com 149,43m² de área privativa, 04 dormitórios (sendo 02 suítes e 02 demi-suítes), finamente mobiliado, decorado e equipado. Possui churrasqueira a carvão, 03 vagas de garagem e área de lazer completa.',
    features: ['Mobiliado, decorado e equipado', 'Churrasqueira a carvão', 'Lazer completo', '3 vagas de garagem'],
    highlighted: true,
    createdAt: '2026-06-19T11:10:00Z',
  },
  {
    id: 'tonino-lamborghini-residence',
    title: 'Tonino Lamborghini Residence',
    slug: 'tonino-lamborghini-residence',
    type: 'apartment',
    category: 'third_party',
    status: 'available',
    price: 8950000,
    area: 194.25,
    bedrooms: 4,
    bathrooms: 5,
    parking: 3,
    address: {
      neighborhood: 'Centro',
      city: 'Balneário Camboriú',
      state: 'SC',
    },
    images: [
      '/images/properties/tonino-lamborghini-residence/26-sacada-tipo-a-norte-tlrbc.jpg',
      '/images/properties/tonino-lamborghini-residence/image_14.png',
      '/images/properties/tonino-lamborghini-residence/image_15.png',
      '/images/properties/tonino-lamborghini-residence/image_16.png',
      '/images/properties/tonino-lamborghini-residence/image_17.png',
      '/images/properties/tonino-lamborghini-residence/image_18.png',
      '/images/properties/tonino-lamborghini-residence/image_19.png',
      '/images/properties/tonino-lamborghini-residence/image_20.png',
      '/images/properties/tonino-lamborghini-residence/image_21.png',
      '/images/properties/tonino-lamborghini-residence/image_22.png',
      '/images/properties/tonino-lamborghini-residence/image_23.png',
      '/images/properties/tonino-lamborghini-residence/image_24.png',
      '/images/properties/tonino-lamborghini-residence/image_25.png',
      '/images/properties/tonino-lamborghini-residence/image_26.png',
      '/images/properties/tonino-lamborghini-residence/image_27.png',
      '/images/properties/tonino-lamborghini-residence/image_28.png',
      '/images/properties/tonino-lamborghini-residence/image_29.png',
      '/images/properties/tonino-lamborghini-residence/image_30.png',
      '/images/properties/tonino-lamborghini-residence/image_31.png',
      '/images/properties/tonino-lamborghini-residence/image_32.png',
      '/images/properties/tonino-lamborghini-residence/image_33.png',
      '/images/properties/tonino-lamborghini-residence/image_34.png',
      '/images/properties/tonino-lamborghini-residence/image_35.png',
      '/images/properties/tonino-lamborghini-residence/image_36.png',
      '/images/properties/tonino-lamborghini-residence/image_37.png',
      '/images/properties/tonino-lamborghini-residence/image_38.png',
      '/images/properties/tonino-lamborghini-residence/image_39.png',
      '/images/properties/tonino-lamborghini-residence/image_40.png',
      '/images/properties/tonino-lamborghini-residence/image_41.png',
      '/images/properties/tonino-lamborghini-residence/image_42.png',
      '/images/properties/tonino-lamborghini-residence/image_43.png',
      '/images/properties/tonino-lamborghini-residence/image_44.png',
      '/images/properties/tonino-lamborghini-residence/image_45.png',
      '/images/properties/tonino-lamborghini-residence/image_46.png',
      '/images/properties/tonino-lamborghini-residence/image_47.png',
      '/images/properties/tonino-lamborghini-residence/image_48.png',
      '/images/properties/tonino-lamborghini-residence/ton-1.jpg'
    ],
    description: 'Apartamento 1301 (Tipo A) no luxuoso Tonino Lamborghini Residence (em obras), em Balneário Camboriú. Conta com 194,25m² de área privativa, 04 suítes, lavabo, amplo living e churrasqueira. Possui sacada e entrada social e de serviço separadas. São 03 vagas de garagem (410 A/B e 424). O empreendimento oferece lazer completo de altíssimo padrão, incluindo pista de carrinhos elétricos, piscinas adulta, infantil e térmica, spa, massagem, espaço grill e muito mais.',
    features: ['4 Suítes', 'Alto Padrão', 'Lazer completo', '3 vagas de garagem'],
    highlighted: true,
    createdAt: '2026-06-19T11:20:00Z',
  },
  {
    id: 'edificio-residencial-hannover',
    title: 'Edifício Residencial Hannover',
    slug: 'edificio-residencial-hannover',
    type: 'apartment',
    category: 'third_party',
    status: 'available',
    price: 2950000,
    area: 130, 
    bedrooms: 3, 
    bathrooms: 3, 
    parking: 2,
    address: {
      neighborhood: 'Centro',
      city: 'Balneário Camboriú',
      state: 'SC',
    },
    images: [
      '/images/properties/edificio-residencial-hannover/IMG_5538.jpeg',
      '/images/properties/edificio-residencial-hannover/IMG_5539.jpeg',
      '/images/properties/edificio-residencial-hannover/IMG_5540.jpeg',
      '/images/properties/edificio-residencial-hannover/IMG_5541.jpeg',
      '/images/properties/edificio-residencial-hannover/IMG_5542.jpeg',
      '/images/properties/edificio-residencial-hannover/IMG_5545.jpeg',
      '/images/properties/edificio-residencial-hannover/IMG_5551.jpeg',
      '/images/properties/edificio-residencial-hannover/IMG_5552.jpeg',
      '/images/properties/edificio-residencial-hannover/IMG_5553.jpeg',
      '/images/properties/edificio-residencial-hannover/IMG_5554.jpeg',
      '/images/properties/edificio-residencial-hannover/IMG_5648.jpeg',
      '/images/properties/edificio-residencial-hannover/IMG_5649.jpeg',
      '/images/properties/edificio-residencial-hannover/IMG_5651.jpeg',
      '/images/properties/edificio-residencial-hannover/IMG_5652.jpeg',
      '/images/properties/edificio-residencial-hannover/IMG_5653.jpeg',
      '/images/properties/edificio-residencial-hannover/IMG_5654.jpeg',
      '/images/properties/edificio-residencial-hannover/IMG_5655.jpeg',
      '/images/properties/edificio-residencial-hannover/IMG_5656.jpeg',
      '/images/properties/edificio-residencial-hannover/IMG_5657.jpeg',
      '/images/properties/edificio-residencial-hannover/IMG_5658.jpeg',
      '/images/properties/edificio-residencial-hannover/IMG_5659.jpeg',
      '/images/properties/edificio-residencial-hannover/IMG_5660.jpeg',
      '/images/properties/edificio-residencial-hannover/IMG_5661.jpeg',
      '/images/properties/edificio-residencial-hannover/IMG_5662.jpeg',
      '/images/properties/edificio-residencial-hannover/IMG_5663.jpeg',
      '/images/properties/edificio-residencial-hannover/IMG_5664.jpeg',
      '/images/properties/edificio-residencial-hannover/IMG_5665.jpeg'
    ],
    description: 'Apartamento 801 no Edifício Residencial Hannover, no coração de Balneário Camboriú. Unidade finamente mobiliada, decorada e equipada. Possui 02 vagas de garagem (42 e 43). Valor de venda: R$ 2.950.000,00.',
    features: ['Mobiliado e decorado', '2 vagas de garagem', 'Centro de BC', 'Alto padrão'],
    highlighted: true,
    createdAt: '2026-06-19T11:30:00Z',
  },
  {
    id: 'edificio-boulevard-brasil',
    title: 'Edifício Boulevard Brasil',
    slug: 'edificio-boulevard-brasil',
    type: 'apartment',
    category: 'third_party',
    status: 'available',
    price: 3800000,
    area: 122,
    bedrooms: 3,
    bathrooms: 4,
    parking: 3,
    address: {
      street: 'Rua 101, n.30',
      neighborhood: 'Centro',
      city: 'Balneário Camboriú',
      state: 'SC',
    },
    images: [
      '/images/properties/edificio-boulevard-brasil/WhatsApp Image 2026-02-05 at 14.44.55.jpeg',
      '/images/properties/edificio-boulevard-brasil/WhatsApp Image 2026-02-05 at 14.44.56 (1).jpeg',
      '/images/properties/edificio-boulevard-brasil/WhatsApp Image 2026-02-05 at 14.44.56 (10).jpeg',
      '/images/properties/edificio-boulevard-brasil/WhatsApp Image 2026-02-05 at 14.44.56 (11).jpeg',
      '/images/properties/edificio-boulevard-brasil/WhatsApp Image 2026-02-05 at 14.44.56 (12).jpeg',
      '/images/properties/edificio-boulevard-brasil/WhatsApp Image 2026-02-05 at 14.44.56 (13).jpeg',
      '/images/properties/edificio-boulevard-brasil/WhatsApp Image 2026-02-05 at 14.44.56 (14).jpeg',
      '/images/properties/edificio-boulevard-brasil/WhatsApp Image 2026-02-05 at 14.44.56 (15).jpeg',
      '/images/properties/edificio-boulevard-brasil/WhatsApp Image 2026-02-05 at 14.44.56 (16).jpeg',
      '/images/properties/edificio-boulevard-brasil/WhatsApp Image 2026-02-05 at 14.44.56 (17).jpeg',
      '/images/properties/edificio-boulevard-brasil/WhatsApp Image 2026-02-05 at 14.44.56 (18).jpeg',
      '/images/properties/edificio-boulevard-brasil/WhatsApp Image 2026-02-05 at 14.44.56 (19).jpeg',
      '/images/properties/edificio-boulevard-brasil/WhatsApp Image 2026-02-05 at 14.44.56 (2).jpeg',
      '/images/properties/edificio-boulevard-brasil/WhatsApp Image 2026-02-05 at 14.44.56 (20).jpeg',
      '/images/properties/edificio-boulevard-brasil/WhatsApp Image 2026-02-05 at 14.44.56 (3).jpeg',
      '/images/properties/edificio-boulevard-brasil/WhatsApp Image 2026-02-05 at 14.44.56 (4).jpeg',
      '/images/properties/edificio-boulevard-brasil/WhatsApp Image 2026-02-05 at 14.44.56 (5).jpeg',
      '/images/properties/edificio-boulevard-brasil/WhatsApp Image 2026-02-05 at 14.44.56 (6).jpeg',
      '/images/properties/edificio-boulevard-brasil/WhatsApp Image 2026-02-05 at 14.44.56 (7).jpeg',
      '/images/properties/edificio-boulevard-brasil/WhatsApp Image 2026-02-05 at 14.44.56 (8).jpeg',
      '/images/properties/edificio-boulevard-brasil/WhatsApp Image 2026-02-05 at 14.44.56 (9).jpeg',
      '/images/properties/edificio-boulevard-brasil/WhatsApp Image 2026-02-05 at 14.44.56.jpeg'
    ],
    description: 'O Edifício Boulevard Brasil é ideal para quem busca uma opção pronta para morar no Centro de Balneário Camboriú, a poucos metros da Praia Central. Com apenas um apartamento por andar, a unidade conta com 122m² de área privativa, 03 suítes (sendo uma master com sacada), lavabo, amplo living e cozinha integrada com espaço gourmet. É finamente mobiliado, decorado e equipado. Possui 03 vagas de garagem. A infraestrutura de lazer é completa, com piscina adulto e infantil, cinema, salões de festas, espaço zen e academia.',
    features: ['1 apartamento por andar', '3 Suítes', 'Lazer completo', '3 vagas de garagem'],
    highlighted: true,
    createdAt: '2026-06-19T11:40:00Z',
  },
  {
    id: 'edificio-imperatriz',
    title: 'Edifício Imperatriz',
    slug: 'edificio-imperatriz',
    type: 'apartment',
    category: 'third_party',
    status: 'available',
    price: 1890000,
    area: 70,
    bedrooms: 2,
    bathrooms: 1,
    parking: 1,
    address: {
      street: 'Av. Atlântica, 2554',
      neighborhood: 'Centro',
      city: 'Balneário Camboriú',
      state: 'SC',
    },
    images: [
      '/images/properties/edificio-imperatriz/IMG_9746.jpeg',
      '/images/properties/edificio-imperatriz/IMG_9747.jpeg',
      '/images/properties/edificio-imperatriz/IMG_9748.jpeg',
      '/images/properties/edificio-imperatriz/IMG_9749.jpeg',
      '/images/properties/edificio-imperatriz/IMG_9751.jpeg',
      '/images/properties/edificio-imperatriz/IMG_9752.jpeg',
      '/images/properties/edificio-imperatriz/IMG_9753.jpeg',
      '/images/properties/edificio-imperatriz/IMG_9754.jpeg',
      '/images/properties/edificio-imperatriz/IMG_9756.jpeg',
      '/images/properties/edificio-imperatriz/IMG_9757.jpeg',
      '/images/properties/edificio-imperatriz/IMG_9758.jpeg',
      '/images/properties/edificio-imperatriz/IMG_9759.jpeg',
      '/images/properties/edificio-imperatriz/IMG_9760.jpeg',
      '/images/properties/edificio-imperatriz/IMG_9761.jpeg',
      '/images/properties/edificio-imperatriz/IMG_9762.jpeg',
      '/images/properties/edificio-imperatriz/IMG_9763.jpeg',
      '/images/properties/edificio-imperatriz/IMG_9764.jpeg'
    ],
    description: 'Apartamento 231 (Torre C) à venda no Edifício Imperatriz, localizado na icônica Av. Atlântica, de frente para o mar. A unidade fica de fundos, sendo totalmente reformada, oferecendo 70m² de área privativa com 02 dormitórios e 01 banheiro, finamente mobiliada, decorada e equipada, além de 01 vaga de garagem. O condomínio dispõe de portaria 24h e lazer completo com piscinas adulta e infantil com vista mar, salão de festas e muito mais.',
    features: ['Frente Mar', 'Mobiliado e decorado', 'Lazer com vista pro mar', 'Portaria 24h'],
    highlighted: true,
    createdAt: '2026-06-19T11:50:00Z',
  },
  {
    id: 'brava-garden-residence',
    title: 'Brava Garden Residence',
    slug: 'brava-garden-residence',
    type: 'apartment',
    category: 'third_party',
    status: 'available',
    price: 3500000,
    area: 133,
    bedrooms: 3,
    bathrooms: 4,
    parking: 2,
    address: {
      street: 'Rua Conselheiro Julio Kumn, n.295',
      neighborhood: 'Praia Brava',
      city: 'Itajaí',
      state: 'SC',
    },
    images: [
      '/images/properties/brava-garden-residence/PHOTO-2026-05-21-17-32-54 (1).jpg',
      '/images/properties/brava-garden-residence/PHOTO-2026-05-21-17-32-54 (10).jpg',
      '/images/properties/brava-garden-residence/PHOTO-2026-05-21-17-32-54 (11).jpg',
      '/images/properties/brava-garden-residence/PHOTO-2026-05-21-17-32-54 (12).jpg',
      '/images/properties/brava-garden-residence/PHOTO-2026-05-21-17-32-54 (13).jpg',
      '/images/properties/brava-garden-residence/PHOTO-2026-05-21-17-32-54 (14).jpg',
      '/images/properties/brava-garden-residence/PHOTO-2026-05-21-17-32-54 (2).jpg',
      '/images/properties/brava-garden-residence/PHOTO-2026-05-21-17-32-54 (3).jpg',
      '/images/properties/brava-garden-residence/PHOTO-2026-05-21-17-32-54 (4).jpg',
      '/images/properties/brava-garden-residence/PHOTO-2026-05-21-17-32-54 (5).jpg',
      '/images/properties/brava-garden-residence/PHOTO-2026-05-21-17-32-54 (6).jpg',
      '/images/properties/brava-garden-residence/PHOTO-2026-05-21-17-32-54 (7).jpg',
      '/images/properties/brava-garden-residence/PHOTO-2026-05-21-17-32-54 (8).jpg',
      '/images/properties/brava-garden-residence/PHOTO-2026-05-21-17-32-54 (9).jpg',
      '/images/properties/brava-garden-residence/PHOTO-2026-05-21-17-32-54.jpg',
      '/images/properties/brava-garden-residence/PHOTO-2026-06-03-16-05-10.jpg',
      '/images/properties/brava-garden-residence/PHOTO-2026-06-03-16-05-11 (1).jpg',
      '/images/properties/brava-garden-residence/PHOTO-2026-06-03-16-05-11 (2).jpg',
      '/images/properties/brava-garden-residence/PHOTO-2026-06-03-16-05-11.jpg'
    ],
    description: 'Lindo apartamento mobiliado, decorado e equipado no Brava Garden Residence, na Praia Brava de Itajaí. São 133m² privativos divididos em 03 suítes confortáveis e 02 vagas de garagem. O empreendimento conta com uma área de lazer completa, decorada e mobiliada, incluindo piscina principal com raia, piscina privativa com espaço gourmet, snooker pub, salão de beleza e quadra poliesportiva.',
    features: ['Mobiliado e decorado', 'Na Praia Brava', 'Piscina privativa e com raia', 'Salão de beleza'],
    highlighted: true,
    createdAt: '2026-06-19T12:00:00Z',
  },
  {
    id: 'residencial-nirvana',
    title: 'Residencial Nirvana',
    slug: 'residencial-nirvana',
    type: 'apartment',
    category: 'third_party',
    status: 'available',
    price: 2450000,
    area: 244.30,
    bedrooms: 3,
    bathrooms: 2,
    parking: 2,
    address: {
      street: 'Rua 2300, n.537',
      neighborhood: 'Centro',
      city: 'Balneário Camboriú',
      state: 'SC',
    },
    images: [
      '/images/properties/residencial-nirvana/IMG_6143.jpeg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-43-59.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-43-59_1.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-43-59_10.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-43-59_11.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-43-59_12.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-43-59_13.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-43-59_14.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-43-59_15.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-43-59_16.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-43-59_17.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-43-59_18.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-43-59_19.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-43-59_2.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-43-59_20.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-43-59_21.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-43-59_22.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-43-59_23.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-43-59_24.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-43-59_25.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-43-59_26.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-43-59_3.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-43-59_4.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-43-59_5.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-43-59_6.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-43-59_7.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-43-59_8.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-43-59_9.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-44-00.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-44-00_1.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-44-00_10.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-44-00_11.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-44-00_2.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-44-00_3.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-44-00_4.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-44-00_5.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-44-00_6.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-44-00_7.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-44-00_8.jpg',
      '/images/properties/residencial-nirvana/PHOTO-2026-06-12-11-44-00_9.jpg'
    ],
    description: 'Apartamento diferenciado (Apto 301) no Residencial Nirvana, localizado no coração de Balneário Camboriú. Com impressionantes 244,30m² de área privativa, o imóvel dispõe de 01 suíte master, 02 dormitórios e amplo living com lareira. É finamente mobiliado, decorado e equipado. O grande destaque é a sua área de festas privativa, que conta com amplos terraços laterais, piscina privativa, fogão e forno a lenha, churrasqueira, além de mesas de jogos e sinuca. Possui 02 vagas de garagem (01 e 07).',
    features: ['Apartamento Diferenciado', 'Piscina Privativa', 'Amplo terraço', 'Fogão e forno a lenha'],
    highlighted: true,
    createdAt: '2026-06-19T12:10:00Z',
  },
  {
    id: 'edificio-marques-de-olinda',
    title: 'Edifício Marquês de Olinda',
    slug: 'edificio-marques-de-olinda',
    type: 'apartment',
    category: 'third_party',
    status: 'available',
    price: 3200000,
    area: 0,
    bedrooms: 2,
    suites: 1,
    bathrooms: 2,
    parking: 2,
    address: {
      street: 'Av. Atlântica nº 2700 esq. 2300, apto 1402A',
      neighborhood: 'Centro',
      city: 'Balneário Camboriú',
      state: 'SC',
    },
    images: [
      '/images/properties/edificio-marques-de-olinda/WhatsApp Image 2026-06-23 at 18.37.17 (1).jpeg',
      '/images/properties/edificio-marques-de-olinda/WhatsApp Image 2026-06-23 at 18.37.17 (2).jpeg',
      '/images/properties/edificio-marques-de-olinda/WhatsApp Image 2026-06-23 at 18.37.17.jpeg',
      '/images/properties/edificio-marques-de-olinda/WhatsApp Image 2026-06-23 at 18.37.18 (1).jpeg',
      '/images/properties/edificio-marques-de-olinda/WhatsApp Image 2026-06-23 at 18.37.18 (2).jpeg',
      '/images/properties/edificio-marques-de-olinda/WhatsApp Image 2026-06-23 at 18.37.18 (3).jpeg',
      '/images/properties/edificio-marques-de-olinda/WhatsApp Image 2026-06-23 at 18.37.18 (4).jpeg',
      '/images/properties/edificio-marques-de-olinda/WhatsApp Image 2026-06-23 at 18.37.18.jpeg'
    ],
    description: 'Apto alto padrão, vista total mar de todos os comodos. 2 dormit. sendo 1 suíte com ar. Móveis claros, sob medida, colchões primeira linha, sala com 4 amb., Home theater, TV Smart 52\', espaço gourmet com cooktop elétrico digital, forno elétrico, microondas, geladeira duplex, lavaroupas, etc. Totalmente mobiliado, equipado e decorado, churrasq. na varanda evidraçada Reiki. Cond. em torno de 850,00 e IPTU 1800,00.',
    features: ['Vista total para o mar', 'Mobiliado, equipado e decorado', 'Alto padrão', 'Churrasqueira na varanda'],
    highlighted: true,
    createdAt: '2026-06-25T17:00:00Z',
  },
  {
    id: 'edificio-alianca',
    title: 'Edifício Alliança',
    slug: 'edificio-alianca',
    type: 'apartment',
    category: 'third_party',
    status: 'available',
    price: 1600000,
    area: 110,
    bedrooms: 2,
    suites: 1,
    bathrooms: 2,
    parking: 1,
    address: {
      street: 'Avenida Atlântica / Avenida Brasil',
      neighborhood: 'Centro',
      city: 'Balneário Camboriú',
      state: 'SC',
    },
    images: [],
    description: 'Acordar e ver o mar pela janela, todos os dias. Esse é o privilégio de morar no Edifício Alliança, um apartamento à venda no Centro de Balneário Camboriú, pronto para morar e totalmente mobiliado. Quadra mar. O imóvel conta com 110m² de área privativa. A sala recebe o sol da manhã e se abre para a vista mar. São 2 quartos e 2 banheiros com box. Conta com ar-condicionado já instalado, 1 vaga de garagem simples e o edifício dispõe de 2 elevadores e salão de festas com churrasqueira.',
    features: [
      'Mobiliado',
      'Ar Condicionado',
      'Cozinha com Armário',
      'Banheiro com Box',
      'Vista para o Mar',
      'Sol Da Manhã',
      'Elevador',
      'Salão de Festas'
    ],
    highlighted: true,
    createdAt: '2026-06-30T10:00:00Z',
  }
];

export function getFilteredProperties(filters?: Record<string, string | undefined>): Property[] {
  let result = [...mockProperties];

  if (!filters) return result;

  if (filters.type) {
    result = result.filter(p => p.type === filters.type);
  }
  if (filters.city) {
    result = result.filter(p => p.address.city.toLowerCase() === filters.city!.toLowerCase());
  }
  if (filters.bedrooms) {
    const beds = parseInt(filters.bedrooms);
    if (beds === 4) {
      result = result.filter(p => p.bedrooms >= 4);
    } else {
      result = result.filter(p => p.bedrooms === beds);
    }
  }
  if (filters.minPrice) {
    result = result.filter(p => p.price >= parseInt(filters.minPrice!));
  }
  if (filters.maxPrice) {
    result = result.filter(p => p.price <= parseInt(filters.maxPrice!));
  }
  if (filters.search) {
    const search = filters.search.toLowerCase();
    result = result.filter(p =>
      p.title.toLowerCase().includes(search) ||
      p.description.toLowerCase().includes(search) ||
      p.address.city.toLowerCase().includes(search) ||
      p.address.neighborhood.toLowerCase().includes(search)
    );
  }

  // Sorting
  if (filters.sort) {
    switch (filters.sort) {
      case 'price_asc':
        result.sort((a, b) => a.price - b.price);
        break;
      case 'price_desc':
        result.sort((a, b) => b.price - a.price);
        break;
      case 'area_desc':
        result.sort((a, b) => b.area - a.area);
        break;
      case 'newest':
        result.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
        break;
    }
  }

  return result;
}

export function getPropertyById(id: string): Property | undefined {
  return mockProperties.find(p => p.id === id);
}

export function getHighlightedProperties(): Property[] {
  return mockProperties.filter(p => p.highlighted);
}

export function getSimilarProperties(property: Property, limit: number = 3): Property[] {
  return mockProperties
    .filter(p => p.id !== property.id && p.type === property.type)
    .slice(0, limit);
}

export function getCities(): string[] {
  const cities = new Set(mockProperties.map(p => p.address.city));
  return Array.from(cities).sort();
}

export function getNeighborhoods(): string[] {
  const neighborhoods = new Set(mockProperties.map(p => p.address.neighborhood));
  return Array.from(neighborhoods).sort();
}
